name          'cesnet-zookeeper'
version       '0.1.0'
source        'http://scientific.zcu.cz/git/cesnet-zookeeper.git'
author        'CESNET'
license       'Apache License, Version 2.0'
summary       'Zookeeper'
description   'Creates zookeeper cluster with enabled security'
project_page  'https://github.com/CESNET/'

dependency 'puppetlabs/stdlib'
