name 'cesnet-zookeeper'
version '1.0.1'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Zookeeper cluster with security'
description 'Zookeeper cluster with security'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <7.0.0'
dependency 'cesnet/hadoop_lib', '>= 0.3.0 <1.0.0'
