name 'cesnet-zookeeper'
version '0.10.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Zookeeper cluster with security'
description 'Zookeeper cluster with security'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-zookeeper'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'cesnet/hadoop_lib', '<1.0.0'
